In [43]:
import random
import numpy as np 

import time
import datetime
import pandas as pd
import os
from tqdm import tqdm

In [44]:
pj_path = os.getenv('HOME') + '/Projects/JeongCheck'
data_path = pj_path + '/prediction_data_nsmc'

In [45]:
file_list = os.listdir(data_path)
print(len(file_list))
file_list

15

['water_pred.csv',
 'art_pred.csv',
 'oworld_pred.csv',
 'observatory_pred.csv',
 'dongchundang_pred.csv',
 'hanbat_pred.csv',
 'yuseong_pred.csv',
 'expo_pred.csv',
 'gyejok_pred.csv',
 'daecheong_pred.csv',
 'jangtae_pred.csv',
 'uineungjeongi_pred.csv',
 'science_pred.csv',
 'ppuri_pred.csv',
 'sungsimdang_pred.csv']

In [46]:
places = []
for file in file_list:
    tmp = file.split('_')[0]
    places.append(tmp)

In [47]:
places

['water',
 'art',
 'oworld',
 'observatory',
 'dongchundang',
 'hanbat',
 'yuseong',
 'expo',
 'gyejok',
 'daecheong',
 'jangtae',
 'uineungjeongi',
 'science',
 'ppuri',
 'sungsimdang']

In [54]:
test = pd.read_csv(data_path + f'/{file_list[0]}')
test.head()

,Unnamed: 0,name,ratings,date,comment,search,keyword,label,pred
0,0,김성주,5,9시간 전,가편하게 산책과 등산을 할 수 있는 곳,계룡산국립공원수통골지구,water_barrel,1,1
1,1,서알콩,5,1일 전,커피 한잔하기 딱 좋은 거리에요,계룡산국립공원수통골지구,water_barrel,1,1
2,2,윤설희,5,2일 전,비 오고 난 수통골,계룡산국립공원수통골지구,water_barrel,1,0
3,3,이상훈,4,2일 전,가족 나들이하기 정말 좋은 곳 국립공원이라 관리도 잘 돼있네요,계룡산국립공원수통골지구,water_barrel,1,1
4,4,송순이공주,5,2일 전,동네라서 자주 가는데 갈 때마다 좋은 곳이에요 이번에는 뱀이 나와서 좀 놀랐어요,계룡산국립공원수통골지구,water_barrel,1,1

In [68]:
# 시간 일 주 달 년 
# 년이 들어가고 & 숫자가 2 초과면 이전, 아니면 이후 

test['date'] = test['date'].apply(lambda row : 'before' if '년' in str(row) and re.sub('[가-힣]', '', str(row)) >= str(2) else 'after')

In [69]:
test.head()

,Unnamed: 0,name,ratings,date,comment,search,keyword,label,pred
0,0,김성주,5,after,가편하게 산책과 등산을 할 수 있는 곳,계룡산국립공원수통골지구,water_barrel,1,1
1,1,서알콩,5,after,커피 한잔하기 딱 좋은 거리에요,계룡산국립공원수통골지구,water_barrel,1,1
2,2,윤설희,5,after,비 오고 난 수통골,계룡산국립공원수통골지구,water_barrel,1,0
3,3,이상훈,4,after,가족 나들이하기 정말 좋은 곳 국립공원이라 관리도 잘 돼있네요,계룡산국립공원수통골지구,water_barrel,1,1
4,4,송순이공주,5,after,동네라서 자주 가는데 갈 때마다 좋은 곳이에요 이번에는 뱀이 나와서 좀 놀랐어요,계룡산국립공원수통골지구,water_barrel,1,1

In [70]:
test[test.date == 'after']

,Unnamed: 0,name,ratings,date,comment,search,keyword,label,pred
0,0,김성주,5,after,가편하게 산책과 등산을 할 수 있는 곳,계룡산국립공원수통골지구,water_barrel,1,1
1,1,서알콩,5,after,커피 한잔하기 딱 좋은 거리에요,계룡산국립공원수통골지구,water_barrel,1,1
2,2,윤설희,5,after,비 오고 난 수통골,계룡산국립공원수통골지구,water_barrel,1,0
3,3,이상훈,4,after,가족 나들이하기 정말 좋은 곳 국립공원이라 관리도 잘 돼있네요,계룡산국립공원수통골지구,water_barrel,1,1
4,4,송순이공주,5,after,동네라서 자주 가는데 갈 때마다 좋은 곳이에요 이번에는 뱀이 나와서 좀 놀랐어요,계룡산국립공원수통골지구,water_barrel,1,1
...,...,...,...,...,...,...,...,...,...
680,680,김태규,4,after,완만한 산책 등산 먹거리 좋아요,수통골유원지,water_barrel,1,1
681,681,김뚱이,5,after,가깝고 깨끗하게 정리도 잘 되어있어서 좋아요,수통골유원지,water_barrel,1,1
682,682,이시형,5,after,가끔 산책하러 가는 수통골이에요,수통골유원지,water_barrel,1,1
683,683,Park Sangbae,4,after,등산을 목적으로 한다면 다녀올만함 여러 코스가 있으니 취향과 체력에 맞춰서 다녀오시...,수통골유원지,water_barrel,0,0
684,684,hyun seung shin,3,after,좋은 산책길 간단한 등산도 가능,수통골유원지,water_barrel,1,1

In [60]:
after_test = test[test.date == 'after']
before_test = test[test.date == 'before']

In [62]:
def sentimentScore(df):
    data_len = len(df)
    data_label = df.label.sum()
    score = (data_label / data_len) *100
    return '%0.2f' %score

- 함수 테스트

In [73]:
score = sentimentScore(test)
score

'94.89'

In [63]:
for place, file_name in zip(places, file_list):
    print(file_name)

water_pred.csv
art_pred.csv
oworld_pred.csv
observatory_pred.csv
dongchundang_pred.csv
hanbat_pred.csv
yuseong_pred.csv
expo_pred.csv
gyejok_pred.csv
daecheong_pred.csv
jangtae_pred.csv
uineungjeongi_pred.csv
science_pred.csv
ppuri_pred.csv
sungsimdang_pred.csv

## 리뷰 개수 확인 및 감성분석 점수 계산

In [72]:
score_dict = {}
for place, file_name in zip(places, file_list):
    tmp_data = pd.read_csv(data_path + f'/{file_name}')
    tmp_data['date'] = tmp_data['date'].apply(lambda row : 'before' if '년' in str(row) and re.sub('[가-힣]', '', str(row)) >= str(2) else 'after')
    
    before_tmp = tmp_data[tmp_data.date == 'before']
    after_tmp = tmp_data[tmp_data.date == 'after']
    print('before len :', len(before_tmp))
    print('after len :', len(after_tmp))
    
    print(f'========= 여행지 : {place} =========')
    bf_score = sentimentScore(before_tmp)
    af_score = sentimentScore(after_tmp)
    
    score_dict[place] = [bf_score, af_score]

before len : 144
after len : 541
========= 여행지 : water =========
before len : 375
after len : 448
========= 여행지 : art =========
before len : 0
after len : 444
========= 여행지 : oworld =========
before len : 11
after len : 15
========= 여행지 : observatory =========
before len : 108
after len : 219
========= 여행지 : dongchundang =========
before len : 0
after len : 402
========= 여행지 : hanbat =========
before len : 40
after len : 389
========= 여행지 : yuseong =========
before len : 269
after len : 511
========= 여행지 : expo =========
before len : 195
after len : 276
========= 여행지 : gyejok =========
before len : 260
after len : 229
========= 여행지 : daecheong =========
before len : 0
after len : 510
========= 여행지 : jangtae =========
before len : 10
after len : 323
========= 여행지 : uineungjeongi =========
before len : 0
after len : 381
========= 여행지 : science =========
before len : 0
after len : 426
========= 여행지 : ppuri =========
before len : 267
after len : 1592
========= 여행지 : sungsimdang =========

/home/aiffel-dj26/anaconda3/envs/aiffel/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in long_scalars
  after removing the cwd from sys.path.

### {여행지 : [코로나 이전감성분석 점수, 코로나 이후 감성분석 점수]}

In [73]:
score_dict

{'water': ['90.28', '96.12'],
 'art': ['78.40', '82.59'],
 'oworld': ['nan', '81.76'],
 'observatory': ['100.00', '86.67'],
 'dongchundang': ['97.22', '91.78'],
 'hanbat': ['nan', '88.56'],
 'yuseong': ['92.50', '89.97'],
 'expo': ['70.26', '77.10'],
 'gyejok': ['95.38', '92.75'],
 'daecheong': ['76.92', '86.46'],
 'jangtae': ['nan', '90.00'],
 'uineungjeongi': ['60.00', '69.04'],
 'science': ['nan', '88.19'],
 'ppuri': ['nan', '85.45'],
 'sungsimdang': ['82.77', '83.42']}